version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: walkicar-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DB:-walkicar}
      MYSQL_USER: ${MYSQL_USER:-walkicar}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-walkicar123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: walkicar-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  livekit:
    image: livekit/livekit-server:latest
    container_name: walkicar-livekit
    ports:
      - "7880:7880"
      - "7881:7881"
    environment:
      LIVEKIT_CONFIG: |
        port: 7880
        rtc:
          udp_port: 7881
          use_external_ip: true
          stun_servers:
            - stun:turn:3478
          turn_servers:
            - host: turn
            - port: 3478
            - username: ${TURN_USER:-walkicar}
            - password: ${TURN_PASSWORD:-walkicar123}
        keys:
          ${LIVEKIT_API_KEY:-devkey}: ${LIVEKIT_API_SECRET:-secret}
        development: true
    depends_on:
      - turn

  turn:
    image: coturn/coturn:latest
    container_name: walkicar-turn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49152-65535:49152-65535/udp"
    environment:
      TURN_USERNAME: ${TURN_USER:-walkicar}
      TURN_PASSWORD: ${TURN_PASSWORD:-walkicar123}
    command: |
      -n
      --log-file=stdout
      --external-ip=$$(detect-external-ip)
      --listening-port=3478
      --tls-listening-port=5349
      --listening-ip=0.0.0.0
      --relay-ip=0.0.0.0
      --realm=walkicar
      --server-name=walkicar
      --user-quota=12
      --total-quota=1200
      --userdb=/etc/turnuserdb.conf
      --lt-cred-mech
      --user=${TURN_USER:-walkicar}:${TURN_PASSWORD:-walkicar123}

  api:
    build: .
    container_name: walkicar-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: ${MYSQL_DB:-walkicar}
      MYSQL_USER: ${MYSQL_USER:-walkicar}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-walkicar123}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_KEY_ID: ${APPLE_KEY_ID}
      APPLE_PRIVATE_KEY: ${APPLE_PRIVATE_KEY}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY:-devkey}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET:-secret}
      LIVEKIT_WS_URL: ws://livekit:7880
    depends_on:
      - mysql
      - redis
      - livekit
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
  redis_data:
